name: Monthly Report

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas yfinance

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute ivy_portfolio_5_SMA12_bestone.ipynb --output executed_notebook.ipynb
          jupyter nbconvert --to markdown executed_notebook.ipynb --output report.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add report.md
          git commit -m 'Automated monthly report update'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
